import { spawn } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
const chromePath=["/Applications/Google Chrome.app/Contents/MacOS/Google Chrome","/Users/jackjesse/.cache/puppeteer/chrome/mac_arm-127.0.6533.88/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing"].find(existsSync);
const profile=mkdtempSync("/tmp/craft-interactions-");const chrome=spawn(chromePath,["--headless","--disable-gpu","--remote-debugging-port=0",`--user-data-dir=${profile}`,"about:blank"],{stdio:"ignore"});const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function port(){for(let i=0;i<60;i++){const p=join(profile,"DevToolsActivePort");if(existsSync(p))return Number(readFileSync(p,"utf8").split("\n")[0]);await wait(100)}throw Error("No Chrome port")}
class CDP{constructor(url){this.id=0;this.pending=new Map;this.events=new Map;this.ws=new WebSocket(url)}async open(){await new Promise((r,j)=>{this.ws.addEventListener("open",r,{once:true});this.ws.addEventListener("error",j,{once:true})});this.ws.addEventListener("message",e=>{const m=JSON.parse(e.data);if(m.id){const p=this.pending.get(m.id);this.pending.delete(m.id);m.error?p.j(Error(m.error.message)):p.r(m.result)}else{(this.events.get(m.method)||[]).forEach(r=>r(m.params));this.events.set(m.method,[])}})}send(method,params={}){const id=++this.id;return new Promise((r,j)=>{this.pending.set(id,{r,j});this.ws.send(JSON.stringify({id,method,params}))})}once(name){return new Promise(r=>this.events.set(name,[...(this.events.get(name)||[]),r]))}}
let cdp;try{const p=await port();const tabs=await fetch(`http://127.0.0.1:${p}/json/list`).then(r=>r.json());cdp=new CDP(tabs[0].webSocketDebuggerUrl);await cdp.open();await cdp.send("Page.enable");await cdp.send("Runtime.enable");const loaded=cdp.once("Page.loadEventFired");await cdp.send("Page.navigate",{url:"http://127.0.0.1:8765/sites/craft-and-caffine/presentation.html"});await loaded;await wait(200);
const expression=`(async()=>{const click=s=>document.querySelector(s).click();const files={open:'index.html',garden:'concept-two.html',board:'concept-three.html',quiet:'concept-four.html',village:'concept-five.html'};const all=[];for(const [key,file] of Object.entries(files)){click('[data-concept="'+key+'"]');await new Promise(r=>setTimeout(r,90));all.push(document.querySelector('.viewer').classList.contains('open')&&document.querySelector('.site-frame').getAttribute('src')===file&&location.hash==='#'+key);click('.viewer-exit')}click('[data-concept="open"]');await new Promise(r=>setTimeout(r,100));document.querySelector('.concept-picker').value='garden';document.querySelector('.concept-picker').dispatchEvent(new Event('change'));await new Promise(r=>setTimeout(r,100));const switched=document.querySelector('.site-frame').getAttribute('src')==='concept-two.html'&&location.hash==='#garden';click('[data-device="phone"]');const phone=document.querySelector('.viewer-stage').classList.contains('phone');click('.choose');const modal=document.querySelector('.selection').classList.contains('open')&&document.querySelector('.selected-name').textContent==='Paper Garden';document.querySelector('#client-notes').value='Keep the craft-led photography.';click('.copy-selection');await new Promise(r=>setTimeout(r,100));const copied=localStorage.getItem('craft-caffeine-selection')?.includes('Keep the craft-led photography.');document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));const modalClosed=!document.querySelector('.selection').classList.contains('open');document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));const viewerClosed=!document.querySelector('.viewer').classList.contains('open');const links=[...document.querySelectorAll('a[href]')].map(a=>a.href);return{all:all.every(Boolean),switched,phone,modal,copied,modalClosed,viewerClosed,links}})()`;
const result=await cdp.send("Runtime.evaluate",{expression,awaitPromise:true,returnByValue:true});const report=result.result.value;if(!Object.entries(report).filter(([k])=>k!=="links").every(([,v])=>v))throw Error(JSON.stringify(report));console.log("Presentation interactions passed: all five open, switch, phone, selection, copy and Escape close.");console.log(`Resolved ${report.links.length} presentation links.`)}finally{cdp?.ws.close();chrome.kill("SIGTERM");await wait(250);rmSync(profile,{recursive:true,force:true})}
